# Generated by Django 4.2.7 on 2023-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_record_accumulated_power_record_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
