# Generated by Django 4.2.7 on 2023-11-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_record_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='avg_cadence_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_combined_pedal_smoothness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_flow',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_fractional_cadence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_left_pco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_left_pedal_smoothness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_left_power_phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_left_power_phase_peak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_left_torque_effectiveness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_power_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_right_pco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_right_pedal_smoothness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_right_power_phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_right_power_phase_peak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_right_torque_effectiveness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_running_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_stance_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_stance_time_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_stance_time_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_step_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_stroke_distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_vertical_oscillation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='avg_vertical_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='end_position_lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='end_position_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='enhanced_avg_altitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='enhanced_avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='enhanced_max_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='enhanced_max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='enhanced_min_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='event_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='first_length_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='intensity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='lap_trigger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='left_right_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='max_cadence_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='max_fractional_cadence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='max_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='max_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='max_power_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='max_running_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='max_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='message_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='normalized_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='num_active_lengths',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='num_lengths',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='stand_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='start_position_lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='start_position_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='sub_sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='swim_stroke',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='time_standing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_ascent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_descent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_elapsed_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_fat_calories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_fractional_ascent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_fractional_cycles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_fractional_descent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_grit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_strides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_timer_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='total_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lap',
            name='wkt_step_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='custom_target_heart_rate_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='custom_target_heart_rate_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='duration_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='duration_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='exercise_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='exercise_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='intensity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='message_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target_hr_zone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='target_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='weight_display_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutstep',
            name='wkt_step_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
