# Generated by Django 4.2.7 on 2023-11-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_activity_distance_activity_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
    ]
