# Generated by Django 4.2.7 on 2023-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_activity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='total_calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
