# Generated by Django 4.2.7 on 2023-11-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_activity_total_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('zone_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zone_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zone_3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zone_4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zone_5', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LactateThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('pace', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
